### ISSUE TITLE
Build apps, not platforms: operational maturity in a box slides

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2022-talks#10]
Hello @OriPekelman, I hope you are well 🙂

Would it be possible for you to share your slides, please?

![thank you](https://media.giphy.com/media/LmHvvCiMaOkxxlhIQk/giphy.gif)

**Comment by OriPekelman** [comment]
Added you (through your **n.sh) email to the Google Slide deck, if you prefer another method I can also attach a pdf or any other format of your liking...

Cheers,

Ori

**Comment by mykiwi** [comment]
Ok! Thank you.

I will export it as a pdf file then.
But if in the future, you set your Google Slide as public, don't hesitate to do a PR on this repo to update the link :smiley:
