### ISSUE TITLE
Building a great product means designing for your users slides

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2022-talks#11]
Hello @nananat, I hope you are well 🙂

Would it be possible for you to share your slides, please?

![thank you](https://media.giphy.com/media/26FPOogenQv5eOZHO/giphy.gif)

**Comment by nicolas-grekas** [comment]
Here they are:
https://www.figma.com/proto/KdNdrVgSqbx7LeFR46cJyI/designing-for-users_batcon
