### ISSUE TITLE
A self-training journey to the Symfony Certification - and beyond slides

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2022-talks#13]
Hello @Ca-Jou, I hope you are well 🙂

Would it be possible for you to share your slides, please?

![thank you](https://media.giphy.com/media/3o6ZteXRkucGt7KOm4/giphy.gif)

**Comment by Ca-Jou** [comment]
Of course! There you go :)

[A self training journey.pdf](https://github.com/SymfonyCon/2022-talks/files/10056756/A.self.training.journey.pdf)
