### ISSUE TITLE
Fighting impostor syndrome: a practical handbook slides

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2022-talks#14]
Hello @Mupsi, I hope you are well 🙂

Would it be possible for you to share your slides, please?

![thank you](https://media.giphy.com/media/3osxYdXvsGw6wT5lIY/giphy.gif)

**Comment by Mupsi** [comment]
Hey! Yes I'm working on a shareable version! I will open a PR for it soon, thanks for creating this!

**Comment by Mupsi** [comment]
Hey, here are my slides in PDF, and PPTX / ODP format for accessibility (but the fonts are messed up in editable format, sorry!)
Thank you for taking care of this! 

- https://github.com/Mupsi/conferences/blob/main/%5BSymfonyCon%202022%5D%20Fighting%20Impostor%20Syndrome:%20A%20Practical%20Handbook.pdf
- https://github.com/Mupsi/conferences/blob/main/%5BSymfonyCon%202022%5D%20Fighting%20Impostor%20Syndrome:%20A%20Practical%20Handbook.pptx
- https://github.com/Mupsi/conferences/blob/main/%5BSymfonyCon%202022%5D%20Fighting%20Impostor%20Syndrome:%20A%20Practical%20Handbook.odp
