### ISSUE TITLE
Bring your own knowledge: The Shopware App System and platform.sh slides

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2022-talks#18]
Hello @ndzoesch, I hope you are well 🙂

Would it be possible for you to share your slides, please?

![thank you](https://media.giphy.com/media/26FPOogenQv5eOZHO/giphy.gif)

**Comment by ndzoesch** [comment]
[edit] that was not an email...

**Comment by mykiwi** [comment]
> In case the links do not work for you let me know.

:wave:, I was unable to access the files

Could you drag&drop the PDF in [GitHub](https://github.com/SymfonyCon/2022-talks/issues/18)?

**Comment by ndzoesch** [comment]
Done. ^^

[ndzoesch_symfonycon_Shopware_apps_2022.pdf](https://github.com/SymfonyCon/2022-talks/files/10069404/ndzoesch_symfonycon_Shopware_apps_2022.pdf)
