### ISSUE TITLE
The Evolution of Symfony: Now and to the Future! slides

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2022-talks#21]
Hello @weaverryan, I hope you are well 🙂

I did not notice any new slides on your [speakerdeck profile](https://speakerdeck.com/weaverryan).
Would it be possible for you to share your slides, please?

![thank you](https://media.giphy.com/media/KGMOaKUInCvaP2An43/giphy.gif)

**Comment by weaverryan** [comment]
How could I resist this 🤣  - see #22.
