### ISSUE TITLE
Unleashing the power of lazy objects in PHP 🪄 slides

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2022-talks#6]
Hello @nicolas-grekas, I hope you are well 🙂

I did not notice any new slides on your [speakerdeck profile](https://speakerdeck.com/nicolasgrekas).
Would it be possible for you to share them, please?

![thank you](https://media.giphy.com/media/pqtDWYmFsadNP4A85n/giphy.gif)

**Comment by nicolas-grekas** [comment]
Here they are: https://speakerdeck.com/nicolasgrekas/unleashing-the-power-of-lazy-objects-in-php ;)
