### ISSUE TITLE
Observability tools: Who's who? slides

### ISSUE THREAD

**Issue by mykiwi** [SymfonyCon/2022-talks#7]
Hello @lolautruche, I hope you are well 🙂

Would it be possible for you to share your slides, please?

![thank you](https://media.giphy.com/media/3vl6tMEyps7XwjFgsj/giphy.gif)

**Comment by lolautruche** [comment]
Here you go
[Observability tools.pdf](https://github.com/SymfonyCon/2022-talks/files/10093124/Observability.tools.pdf)
